# Generated by Django 5.1 on 2024-10-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='direccion_despacho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appmenu.direccion'),
        ),
    ]
