# Generated by Django 5.1 on 2024-09-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
    ]
