# Generated by Django 5.1 on 2024-09-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmenu', '0002_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comprador', models.CharField(max_length=100)),
                ('apellido_comprador', models.CharField(max_length=100)),
                ('direccion_despacho', models.CharField(max_length=255)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('completo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_minimo_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('despacho_gratis', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Appmenu.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appmenu.producto')),
            ],
        ),
    ]
