# Generated by Django 5.1 on 2024-09-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmenu', '0003_carrito_descuento_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='valor_envio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='valor_minimo_compra',
            field=models.IntegerField(),
        ),
    ]
