# Generated by Django 5.1 on 2024-09-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmenu', '0005_cupondescuento_delete_descuento_alter_carrito_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupondescuento',
            name='despacho_gratis',
            field=models.BooleanField(default=False),
        ),
    ]
